### ISSUE TITLE
why send me to other place

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/askbot-openmooc#7]
In https://questions.domain.com/germany-for-colombians/questions/ i take "ir al curso" and send me to http://questions.domain.com/course/germany-for-colombians/, why, correct path is http://moocng.domain.com/course/germany-for-colombians/, tnks for all

**Comment by ant30** [comment]
Please, this use maillist.
Your askbot settings for that course is not correct.

**Comment by johnfelipe** [comment]
what could be??
